### ISSUE TITLE
NumberFormatException in cafe search

### ISSUE THREAD

**Issue by yeoupooh** [yeoupooh/sandbox-kotlin#1]
```
Exception in thread "Thread-1" java.lang.NumberFormatException: For input string: "-"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:484)
    at java.lang.Integer.parseInt(Integer.java:527)
    at com.subakstudio.sandbox.cafenotifier.search.CafeSearch.search(CafeSearch.kt:56)
    at com.subakstudio.sandbox.cafenotifier.CafeNotifier.updateCafe(CafeNotifier.kt:122)
    at com.subakstudio.sandbox.cafenotifier.CafeNotifier.access$updateCafe(CafeNotifier.kt:17)
    at com.subakstudio.sandbox.cafenotifier.CafeNotifier$start$1.invoke(CafeNotifier.kt:54)
    at com.subakstudio.sandbox.cafenotifier.CafeNotifier$start$1.invoke(CafeNotifier.kt:17)
    at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)


```

**Comment by yeoupooh** [comment]
It need to handle when view count is "-".
